services:
  mysql:
    image: mysql:8.0
    container_name: mysql_gestortareas
    restart: always
    environment:
      MYSQL_DATABASE: gestortareas
      MYSQL_ROOT_PASSWORD: emili123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
    container_name: app_gestortareas
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gestortareas
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: emili123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true

volumes:
  mysql_data:
